config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title
  
  has_many :blogs
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  layout 'blog'
  def index
    @topics = Topic.all
  end

  def show
    @topic= Topic.find(params[:id])
    
    if logged_in?(:site_admin)
      @blogs = @topic.blogs.recent.page(params[:page]).per(5)
    else
      @blogs = @topic.blogs.published.recent.page(params[:page]).per(5)
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_topic.html.erb
<div>
  <%= link_to topic.title, topic_path(topic) %>
</div>

app/views/topics/index.html.erb
<div class="col-sm-8 blog-main">
  
  <h1>topics</h1>

  <% render @topics %>
</div>

app/views/topics/show.html.erb
<div class="col-sm-8 blog-main">
  
  <h1><%= @topic.title %></h1>

  <% paginate @blogs %>
  <%= render @blogs %>
  <% paginate @blogs %>
    
</div>